# Generated by Django 3.1.2 on 2021-11-30 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='profile',
        ),
    ]
