# Generated by Django 3.1.2 on 2022-01-24 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lesson', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=1)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qstats', to='lesson.question')),
            ],
        ),
        migrations.CreateModel(
            name='RepetitionSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(null=True)),
                ('finish_at', models.DateTimeField(null=True)),
                ('pause_started_at', models.DateTimeField(null=True)),
                ('pause_stopped_at', models.DateTimeField(null=True)),
                ('is_started', models.BooleanField(default=False)),
                ('is_ended', models.BooleanField(default=False)),
                ('is_paused', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
                ('questions', models.ManyToManyField(related_name='rep_sessions', through='repeat.QState', to='lesson.Question')),
            ],
        ),
        migrations.AddField(
            model_name='qstate',
            name='rep_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qstats', to='repeat.repetitionsession'),
        ),
    ]
