# Generated by Django 3.1.2 on 2022-01-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repeat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repetitionsession',
            name='rep_mod',
            field=models.CharField(choices=[('M', 'Mix'), ('G', 'Goal'), ('S', 'Section'), ('T', 'Theme')], max_length=7, null=True),
        ),
    ]
