# Generated by Django 3.1.2 on 2022-01-27 12:48

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('repeat', '0002_repetitionsession_rep_mod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repetitionsession',
            name='start_at',
        ),
        migrations.AddField(
            model_name='repetitionsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repetitionsession',
            name='edited_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='repetitionsession',
            name='finish_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
