# Generated by Django 3.1.2 on 2022-01-28 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repeat', '0003_auto_20220127_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repetitionsession',
            old_name='finish_at',
            new_name='finished_at',
        ),
    ]
