# Generated by Django 3.1.2 on 2022-01-27 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='next_repeat_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='question',
            name='prev_repeat_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
