# Generated by Django 3.1.2 on 2022-01-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='edited',
            new_name='edited_at',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='repeated_count_in_last_cicle',
            new_name='repeated_count_in_last_cycle',
        ),
        migrations.AlterField(
            model_name='question',
            name='score',
            field=models.FloatField(null=True),
        ),
    ]
