# Generated by Django 3.1.2 on 2022-01-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_auto_20220117_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='repeated_count',
        ),
        migrations.RemoveField(
            model_name='question',
            name='repeated_count_in_last_cycle',
        ),
        migrations.AddField(
            model_name='question',
            name='cycle',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='memo_index',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='next_repeat_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='prev_repeat_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='repeated_num',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
